### ISSUE TITLE
underscores in distribution name

### ISSUE THREAD

**Issue by hparfr** [acsone/manifestoo-core#68]
Hi @sbidoul 

I have some issues on a non-OCA repo where the ci is trying to install modules like "odoo14-addon-shopinvader_delivery_carrier" instead of "odoo14-addon-shopinvader-delivery-carrier"

I see there is no `replace("_","-")` in `addon_name_to_distribution_name`.

I don't get it why it works in OCA, and what I'm missing.

**Comment by sbidoul** [comment]
Hi @hparfr

Both form work. Try for instance `pip install --dry-run --no-deps odoo14-addon-shopinvader_delivery_carrier`.

What problem do you observe?

**Comment by hparfr** [comment]
Thanks !

I remember having issues with `pip install odoo14-addons-names_with_underscores` . But yes, I  see now both are accepted by `pip`.

In fact, the real problem was the index:
```
pip install --dry-run --no-deps odoo14-addon-shopinvader
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
ERROR: Could not find a version that satisfies the requirement odoo14-addon-shopinvader (from versions: none)
ERROR: No matching distribution found for odoo14-addon-shopinvader
```

**Comment by hparfr** [comment]
I just discovered its existence :)

Thanks for your help.

I just did an `copier copy gh:oca/oca-addons-repo-template . --trust` in some repo in hope to do the minimum changes as possible :)

**Comment by sbidoul** [comment]
This is controlled with the PIP_INDEX_URL environment variable of the [oca-ci image](https://github.com/oca/oca-ci).

**Comment by sbidoul** [comment]
So you can set `PIP_INDEX_URL=https://pypi.org/simple/` to use regular PyPI, for instance.

**Comment by hparfr** [comment]
I did a small edit  in .github/workflows/test.yml

```diff

  test:
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py3.6-ocb14.0:latest
            name: test with OCB
            makepot: "false"
+    env:
+      PIP_EXTRA_INDEX_URL: "https://wheelhouse.shopinvader.com/simple/"
```
