### ISSUE TITLE
Manifest.category raises an error if category isn't set in manifest.

### ISSUE THREAD

**Issue by AnizR** [acsone/manifestoo-core#77]
`Manifest.category` raises an error if category isn't set in manifest.

But, in the [documentation](https://manifestoo-core.readthedocs.io/en/latest/api.html#manifestoo_core.manifest.Manifest.category) category is defined as `str` or `None`.

**Comment by sbidoul** [comment]
Hm, that's weird. I added a test for that and it passes (https://github.com/acsone/manifestoo-core/pull/85).

Do you remember how you had that error?

**Comment by AnizR** [comment]
I had the error at this line in my code: https://github.com/acsone/odoo-sort-manifest-depends/pull/9/files#diff-8067500c0f9c3d2a6189cd0a74c937ef50dc50639d24303f90b3dfb47f087d66R92

but it seems to be fixed :+1:
